set -g mouse on

# Tmux for LunarVim
if-shell 'infocmp $TERM' { set default-terminal "$TERM" } { set default-terminal tmux-256color }
set -a terminal-features '*:RGB'
set -a terminal-features '*:usstyle'
set -ga terminal-overrides ",alacritty:RGB"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
set -g extended-keys on

# setting the plugins up
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# setting other usefull plugins up
set -g @plugin 'ChanderG/tmux-notify'


# setting the status bar
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'moon'

# styling
set -g @rose_pine_host 'on'
set -g @rose_pine_date_time '%H:%M - %d/%m/%Y'

set -g status-position top

# initialize the plugins
run '~/.tmux/plugins/tpm/tpm'
